package com.wen.magi.baseframe.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wen.magi.baseframe.models.Consume;
import com.wen.magi.baseframe.models.Income;

import com.wen.magi.baseframe.db.ConsumeDao;
import com.wen.magi.baseframe.db.IncomeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig consumeDaoConfig;
    private final DaoConfig incomeDaoConfig;

    private final ConsumeDao consumeDao;
    private final IncomeDao incomeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        consumeDaoConfig = daoConfigMap.get(ConsumeDao.class).clone();
        consumeDaoConfig.initIdentityScope(type);

        incomeDaoConfig = daoConfigMap.get(IncomeDao.class).clone();
        incomeDaoConfig.initIdentityScope(type);

        consumeDao = new ConsumeDao(consumeDaoConfig, this);
        incomeDao = new IncomeDao(incomeDaoConfig, this);

        registerDao(Consume.class, consumeDao);
        registerDao(Income.class, incomeDao);
    }
    
    public void clear() {
        consumeDaoConfig.clearIdentityScope();
        incomeDaoConfig.clearIdentityScope();
    }

    public ConsumeDao getConsumeDao() {
        return consumeDao;
    }

    public IncomeDao getIncomeDao() {
        return incomeDao;
    }

}
